version: '3.8'  

services:  
  frontend:  
    build:  
      dockerfile: ./front/Dockerfile  
    ports:  
      - "85:3000"  
    volumes:  
      - ./front:/app  
    environment:  
      - NODE_ENV=development  